const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {summarizeManagement}=require('../src/controllers/managementReportController');
const from='2026-09-20T21:00:00Z',to='2026-09-22T21:00:00Z';
const b={id:1,status:'completed',amount_due:'100',amount_paid:'25',branch_id:1,branch_name:'A',service_id:1,service_name:'Massage',provider_id:1,provider_name:'P',created_at:from};
test('collections reconcile by method, branch, service, provider and day including old bookings',()=>{const payments=[{...b,amount:40,method:'cash'},{...b,branch_id:2,service_id:2,provider_id:2,amount:60,method:'card'}];const r=summarizeManagement([b],payments,from,to);for(const group of ['branches','services','providers','methods','days'])assert.equal(r[group].reduce((n,x)=>n+x.collected,0),100);assert.equal(r.totals.outstanding,75);assert.equal(r.totals.bookingValue,100);assert.equal(r.branches.find(x=>x.id===2).bookings,0);assert.equal(r.days[0].name,'2026-09-21');});
test('empty periods and cancelled debts are represented honestly',()=>{const e=summarizeManagement([],[],from,to);assert.equal(e.totals.collected,0);assert.equal(e.days.length,2);const r=summarizeManagement([{...b,status:'cancelled'}],[],from,to);assert.equal(r.totals.bookingValue,0);assert.equal(r.totals.outstanding,0);assert.equal(r.totals.cancelled,1);});
function setup(){const queries=[];const client={release(){},query:async(sql,args)=>{queries.push({sql,args});return {rows:sql.startsWith('SELECT name')?[{name:'Branch 7'}]:[]}}};const sandbox={module:{exports:{}},console,require:()=>({pool:{connect:async()=>client}})};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/controllers/managementReportController.js'),'utf8'),sandbox);return {handler:sandbox.module.exports.getManagement,queries};}
const response=()=>({code:200,status(c){this.code=c;return this},json(body){this.body=body;return this}});
test('receptionist cannot override assigned branch and report reads one snapshot',async()=>{const {handler,queries}=setup(),res=response();await handler({user:{role:'receptionist',branchId:7},query:{from,to,branchId:'99'}},res);assert.equal(res.code,200);assert.equal(res.body.scope.branchId,7);for(const q of queries.filter(q=>q.sql.includes('FROM bookings b')||q.sql.includes('FROM payments p')))assert.equal(q.args[2],7);assert.match(queries[0].sql,/REPEATABLE READ READ ONLY/);assert.equal(queries.at(-1).sql,'COMMIT');});
test('missing branch and invalid date ranges fail without reading data',async()=>{const {handler,queries}=setup();const a=response();await handler({user:{role:'receptionist'},query:{from,to}},a);assert.equal(a.code,403);const b=response();await handler({user:{role:'admin'},query:{from:'invalid',to}},b);assert.equal(b.code,400);assert.equal(queries.length,0);});
