from pathlib import Path
p=Path('frontend/app/admin/services/page.tsx')
s=p.read_text(encoding='utf-8')
s=s.replace("  const { branches }", "  const [showServiceForm, setShowServiceForm] = useState(false);\n  const [search, setSearch] = useState('');\n  const [busy, setBusy] = useState(false);\n  const { branches }")
s=s.replace("    const query = includeHidden", "    setLoading(true);\n    try {\n    const query = includeHidden")
s=s.replace("    setLoading(false);\n  }", "    } catch { setError('Could not load the service catalog. Please refresh to try again.'); }\n    finally { setLoading(false); }\n  }")
s=s.replace("    setFilterBranch('');", "    setFilterBranch('');\n    setSearch('');")
s=s.replace("    e.preventDefault();\n    setError(null);", "    e.preventDefault();\n    if (busy) return;\n    setBusy(true);\n    setError(null);")
s=s.replace("      setForm(EMPTY_FORM);", "      setForm(EMPTY_FORM);\n      setShowServiceForm(false);")
s=s.replace("'Could not create the service.');\n    }", "'Could not create the service.');\n    } finally { setBusy(false); }")
s=s.replace("'Could not create the category.');\n    }", "'Could not create the category.');\n    } finally { setBusy(false); }")
s=s.replace("    await api.patch(`/services/${service.id}`, { is_active: !service.is_active });\n    load(showHidden);", "    setError(null);\n    try { await api.patch(`/services/${service.id}`, { is_active: !service.is_active }); await load(showHidden); }\n    catch (err) { setError(err instanceof ApiError ? err.message : 'Could not update the service.'); }")
s=s.replace("    await api.patch(`/services/${service.id}`, { [field]: value ? Number(value) : null });\n    load(showHidden);", "    setError(null);\n    try { await api.patch(`/services/${service.id}`, { [field]: value ? Number(value) : null }); await load(showHidden); }\n    catch (err) { setError(err instanceof ApiError ? err.message : 'Could not update the service.'); }")
s=s.replace("  for (const s of services) {", "  categories.forEach(category => allGrouped.set(category.name, []));\n  for (const s of services) {\n    if (search.trim() && !`${s.name} ${s.category_name || 'Other'}`.toLowerCase().includes(search.trim().toLowerCase())) continue;")
s=s.replace("const groupNames = [...allGrouped.keys()]", "const groupNames = [...allGrouped.keys()].filter(name => !search.trim() || allGrouped.get(name)!.length > 0 || name.toLowerCase().includes(search.trim().toLowerCase()))")
s=s.replace("!filterBranch || String(s.branch_id || '') === filterBranch", "!filterBranch || !s.branch_id || String(s.branch_id) === filterBranch")
s=s.replace('    <div>\n      <div className="flex items-start', '    <div className="service-catalog-page">\n      <div className="flex items-start',1)
s=s.replace('<h1 className="font-display text-3xl">Services</h1>', '<div><p className="visits-eyebrow">TREATMENT CATALOG</p><h1 className="font-display text-3xl">Services</h1></div>\n        <div className="flex gap-2"><button className="visits-button" aria-expanded={showServiceForm} aria-controls="service-create-form" onClick={() => setShowServiceForm(!showServiceForm)}>{showServiceForm ? \'Close form\' : \'+ Add service\'}</button>')
s=s.replace("{showCategoryForm ? 'Cancel' : '+ New category'}\n        </button>", "{showCategoryForm ? 'Cancel' : '+ New category'}\n        </button></div>")
s=s.replace('        The treatment menu customers can be booked into, grouped by category so the list stays manageable as it\n        grows. Open a category to see and manage the services inside it.', '        Organize treatments, prices and duration. Open a category to manage its services and branch availability.')
s=s.replace('      {showCategoryForm && (', '''      <div className="service-catalog-summary"><span><strong>{services.filter(s => s.is_active).length}</strong> active services</span><span><strong>{categories.length}</strong> categories</span><span>Prices in TZS · Duration in minutes</span></div>
      {error && <p role="alert" className="visits-error mb-4">{error}</p>}
      {showCategoryForm && (''')
s=s.replace('      <form onSubmit={createService}', '      {showServiceForm && <form id="service-create-form" onSubmit={createService}')
s=s.replace('      </form>\n\n      <label', '      </form>}\n\n      <div className="service-catalog-toolbar"><input type="search" aria-label="Search services and categories" placeholder="Search services or categories" value={search} onChange={e => setSearch(e.target.value)} />\n      <label')
s=s.replace('      </label>\n\n      {loading', '      </label></div>\n\n      {loading')
s=s.replace('<button type="submit"', '<button type="submit" disabled={busy}')
s=s.replace('          {error && <span className="ml-3 text-sm text-clay">{error}</span>}', '')
s=s.replace('className="text-left bg-white rounded-xl2', 'className="service-category-card text-left bg-white rounded-xl2')
s=s.replace('<h2 className="font-display text-lg mb-1">{groupName}</h2>', '<div className="service-category-top"><span aria-hidden="true">✦</span><span aria-hidden="true">↗</span></div><h2 className="font-display text-lg mb-1">{groupName}</h2>')
s=s.replace('                </p>\n              </button>', '''                </p>
                <p className="service-category-price">{items.length ? `From ${new Intl.NumberFormat('en-TZ').format(Math.min(...items.map(s => Number(s.price))))} TZS` : 'Ready for your first service'}</p>
              </button>''')
s=s.replace('No services yet — add one above.', 'No matching categories or services. Add a service or adjust your search.')
s=s.replace('              value={filterBranch}', '              aria-label="Filter services by branch"\n              value={filterBranch}')
s=s.replace('              value={sortBy}', '              aria-label="Sort services"\n              value={sortBy}')
s=s.replace('                          value={s.category_id', '                          aria-label={`Category for ${s.name}`}\n                          value={s.category_id')
s=s.replace('                          value={s.branch_id', '                          aria-label={`Branch for ${s.name}`}\n                          value={s.branch_id')
p.write_text(s,encoding='utf-8')
