process.chdir(__dirname);
const fs=require('fs'),vm=require('vm'),React=require('../frontend/node_modules/react'),server=require('../frontend/node_modules/react-dom/server'),ts=require('../frontend/node_modules/typescript');
let hook=0;
const react={...React,useEffect(){},useState(initial){hook++;return [hook===4?true:typeof initial==='function'?initial():initial,()=>{}]}};
function load(file){const box={module:{exports:{}},exports:{},require(name){if(name==='react')return react;if(name==='react/jsx-runtime')return require('../frontend/node_modules/react/jsx-runtime');if(name==='framer-motion')return {motion:{div:({children})=>React.createElement('div',null,children)}};if(name==='next/link')return {default:({children,...props})=>React.createElement('a',props,children),__esModule:true};if(name==='next/navigation')return {usePathname:()=>'/admin'};if(name==='@/context/AuthContext')return {useAuth:()=>({user:{name:'Admin',email:'admin@serenespa.com',role:'admin'},logout(){}})};if(name.endsWith('DashboardShell'))return load('../frontend/components/DashboardShell.tsx');if(name.endsWith('icons'))return load('../frontend/components/icons.tsx');if(name.endsWith('RoleGuard'))return {default:({children})=>children,__esModule:true};if(name.endsWith('PushToggle'))return {default:()=>React.createElement('p',{style:{fontSize:12,marginTop:12}},'Turn on phone alerts'),__esModule:true};return {default:()=>null,__esModule:true};}};box.exports=box.module.exports;vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2021,esModuleInterop:true}}).outputText,box);return box.module.exports;}
const C=load('../frontend/app/admin/layout.tsx').default;
const css=fs.readFileSync('../frontend/.next/static/css/app/layout.css','utf8')+fs.readFileSync('../frontend/app/globals.css','utf8').split('/* Shared workspace navigation */')[1];
fs.writeFileSync('preview.html','<!doctype html><html><head><meta charset="utf-8"><style>'+css+'body{margin:0;background:#fdfcf9;font-family:Arial;--font-display:Georgia}</style></head><body>'+server.renderToStaticMarkup(React.createElement(C,null,React.createElement('h1',null,'Workspace overview')))+'</body></html>');

