'use client';

import { useEffect, useState, type ReactNode } from 'react';
import { api } from '@/lib/api';
import { downloadCsv } from '@/lib/csv';
import { useAuth } from '@/context/AuthContext';
import type { Branch, User, Service } from '@/lib/types';
import type { ManagementReport, ManagementBooking, ManagementPayment, ManagementRow } from '@/lib/managementReport';

const money = (n: number) => new Intl.NumberFormat('en-TZ', {minimumFractionDigits: 0, maximumFractionDigits: 2}).format(n);
const localDate = () => new Date(Date.now() + 10800000).toISOString().slice(0,10);
const date = (s: string) => new Date(s).toLocaleDateString('en-GB', {day:'2-digit',month:'short',year:'numeric',timeZone:'Africa/Nairobi'});
const stamp = (s: string) => new Date(s).toLocaleString('en-GB', {day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Africa/Nairobi'});
const status = (s: string) => s.replaceAll('_',' ');
function periodRange(preset: string, from: string, to: string) {
  const now = new Date(), eat = new Date(now.getTime() + 10800000);
  let start = `${localDate()}T00:00:00+03:00`;
  if (preset === 'week') {eat.setUTCDate(eat.getUTCDate() - (eat.getUTCDay() + 6) % 7); start = `${eat.toISOString().slice(0,10)}T00:00:00+03:00`;}
  if (preset === 'month') start = `${localDate().slice(0,7)}-01T00:00:00+03:00`;
  if (preset === 'year') start = `${localDate().slice(0,4)}-01-01T00:00:00+03:00`;
  const a = Date.parse(preset === 'custom' ? `${from}T00:00:00+03:00` : start);
  const b = preset === 'custom' ? Math.min(Date.parse(`${to}T00:00:00+03:00`) + 86400000, now.getTime()) : now.getTime();
  if (!Number.isFinite(a) || !Number.isFinite(b) || b <= a || b-a > 367*86400000) throw new Error('Choose a valid date range of up to one year.');
  return {from: new Date(a).toISOString(), to: new Date(b).toISOString()};
}
function Section({index,title,note,children}: {index:string;title:string;note?:string;children:ReactNode}) {
  return <section className="report-section"><div className="report-section-heading"><span>{index}</span><div><h2>{title}</h2>{note && <p>{note}</p>}</div></div>{children}</section>;
}
function Table({headers,children}: {headers:string[];children:ReactNode}) {return <div className="report-table-scroll"><table className="report-table"><thead><tr>{headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
function None({cols}: {cols:number}) {return <tr><td colSpan={cols} className="report-empty">No records for this period and scope.</td></tr>;}
function Performance({rows,label}: {rows:ManagementRow[];label:string}) {return <Table headers={[label,'Bookings','Completed','Collected (TZS)']} >{rows.length ? rows.map(r=><tr key={r.id ?? r.name}><td>{r.name}</td><td className="numeric">{r.bookings}</td><td className="numeric">{r.completed}</td><td className="numeric">{money(r.collected)}</td></tr>) : <None cols={4}/>}</Table>;}
function change(a:number,b:number) {return b ? `${a>=b?'+':''}${((a-b)/b*100).toFixed(1)}%` : a ? 'No prior activity' : 'No change';}

export default function ExecutiveReportView({allowBranchFilter=false}: {allowBranchFilter?:boolean}) {
  const {user} = useAuth();
  const [preset,setPreset] = useState(allowBranchFilter ? 'month' : 'today');
  const [from,setFrom]=useState(localDate()),[to,setTo]=useState(localDate());
  const [branch,setBranch]=useState(''),[provider,setProvider]=useState(''),[service,setService]=useState('');
  const [branches,setBranches]=useState<Branch[]>([]),[providers,setProviders]=useState<User[]>([]),[services,setServices]=useState<Service[]>([]);
  const [includeBookings,setIncludeBookings]=useState(false),[includePayments,setIncludePayments]=useState(false),[notes,setNotes]=useState('');
  const [loading,setLoading]=useState(false),[error,setError]=useState('');
  const [result,setResult]=useState<{data:ManagementReport;provider:string;service:string;notes:string;bookings:boolean;payments:boolean;preparedBy:string}|null>(null);
  useEffect(()=>{let live=true;Promise.all([allowBranchFilter?api.get<{branches:Branch[]}>('/branches'):Promise.resolve({branches:[]}),api.get<{users:User[]}>('/users?role=provider'),api.get<{services:Service[]}>('/services')]).then(([b,p,s])=>{if(live){setBranches(b.branches);setProviders(p.users);setServices(s.services);}}).catch(()=>{if(live)setError('Some filters could not be loaded. Refresh the page to try again.');});return()=>{live=false};},[allowBranchFilter]);
  async function generate() {
    setLoading(true);setError('');
    try {
      const range=periodRange(preset,from,to), query=new URLSearchParams(range);
      if(allowBranchFilter&&branch)query.set('branchId',branch);if(provider)query.set('providerId',provider);if(service)query.set('serviceId',service);
      const data=await api.get<ManagementReport>(`/reports/management?${query}`);
      setResult({data,provider:providers.find(p=>String(p.id)===provider)?.name||'All providers',service:services.find(s=>String(s.id)===service)?.name||'All services',notes,bookings:includeBookings,payments:includePayments,preparedBy:user?.name||'Staff'});
    }catch(e){setError(e instanceof Error?e.message:'Could not generate the report.');}finally{setLoading(false);}
  }
  function exportBookings(){if(!result)return;downloadCsv(`spa-bookings-${result.data.range.from.slice(0,10)}.csv`,[
    {label:'Booking ID',value:(r:ManagementBooking)=>r.id},{label:'Date (EAT)',value:(r:ManagementBooking)=>stamp(r.created_at)},{label:'Customer',value:(r:ManagementBooking)=>r.customer_name},{label:'Phone',value:(r:ManagementBooking)=>r.customer_phone},{label:'Branch',value:(r:ManagementBooking)=>r.branch_name},{label:'Service',value:(r:ManagementBooking)=>r.service_name},{label:'Extra services',value:(r:ManagementBooking)=>r.extra_services},{label:'Room',value:(r:ManagementBooking)=>r.room_name},{label:'Provider',value:(r:ManagementBooking)=>r.provider_name},{label:'Status',value:(r:ManagementBooking)=>r.status},{label:'Value (TZS)',value:(r:ManagementBooking)=>r.amount_due},{label:'Paid to date (TZS)',value:(r:ManagementBooking)=>r.amount_paid},{label:'Outstanding (TZS)',value:(r:ManagementBooking)=>r.status==='cancelled'?0:Math.max(0,Number(r.amount_due)-Number(r.amount_paid))}],result.data.bookings);}
  function exportPayments(){if(!result)return;downloadCsv(`spa-payments-${result.data.range.from.slice(0,10)}.csv`,[
    {label:'Payment ID',value:(r:ManagementPayment)=>r.id},{label:'Booking ID',value:(r:ManagementPayment)=>r.booking_id},{label:'Received (EAT)',value:(r:ManagementPayment)=>stamp(r.created_at)},{label:'Customer',value:(r:ManagementPayment)=>r.customer_name},{label:'Branch',value:(r:ManagementPayment)=>r.branch_name},{label:'Method',value:(r:ManagementPayment)=>r.method},{label:'Amount (TZS)',value:(r:ManagementPayment)=>r.amount},{label:'Recorded by',value:(r:ManagementPayment)=>r.recorded_by_name}],result.data.payments);}
  const r=result?.data;
  const outstanding=r?.bookings.filter(b=>b.status!=='cancelled'&&Number(b.amount_due)>Number(b.amount_paid))||[];
  const input='w-full rounded-lg border border-forest-200 bg-white px-3 py-2.5 text-sm';
  return <div className="space-y-6 pb-8">
    <div className="no-print"><p className="text-[10px] uppercase tracking-[0.22em] text-forest-500 font-semibold mb-2">Serene Spa · Reporting</p><h1 className="font-display text-4xl">{allowBranchFilter?'Management reports':'Branch reports'}</h1><p className="text-sm text-forest-500 mt-2">A clear record of business performance, collections, and follow-up actions.</p></div>
    <form onSubmit={e=>{e.preventDefault();generate();}} className="no-print rounded-2xl border border-forest-100 bg-white p-5 sm:p-6 space-y-5">
      <div className="flex justify-between gap-3"><h2 className="font-semibold text-sm">Prepare your report</h2><span className="text-xs text-forest-500">All times in EAT · Currency TZS</span></div>
      <fieldset disabled={loading} className="space-y-5"><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><label className="text-xs font-medium text-forest-600 space-y-2"><span className="block">Reporting period</span><select value={preset} onChange={e=>setPreset(e.target.value)} className={input}><option value="today">Today</option><option value="week">This week</option><option value="month">This month</option><option value="year">This year</option><option value="custom">Custom dates</option></select></label>{allowBranchFilter?<label className="text-xs font-medium text-forest-600 space-y-2"><span className="block">Branch</span><select value={branch} onChange={e=>{setBranch(e.target.value);setProvider('');}} className={input}><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>:<div className="text-xs text-forest-600"><span className="block mb-2">Branch</span><p className="rounded-lg bg-forest-50 px-3 py-3 text-sm">{user?.branch_name||'Your assigned branch'}</p></div>}<label className="text-xs font-medium text-forest-600 space-y-2"><span className="block">Provider</span><select value={provider} onChange={e=>setProvider(e.target.value)} className={input}><option value="">All providers</option>{providers.filter(p=>!branch||String(p.branch_id)===branch).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs font-medium text-forest-600 space-y-2"><span className="block">Service</span><select value={service} onChange={e=>setService(e.target.value)} className={input}><option value="">All services</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
      {preset==='custom'&&<div className="flex flex-wrap gap-4"><label className="text-xs">From<input required type="date" value={from} max={to} onChange={e=>setFrom(e.target.value)} className={input}/></label><label className="text-xs">To<input required type="date" value={to} min={from} max={localDate()} onChange={e=>setTo(e.target.value)} className={input}/></label></div>}
      <div className="flex flex-wrap gap-x-6 gap-y-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={includeBookings} onChange={e=>setIncludeBookings(e.target.checked)}/>Include booking register</label><label className="flex items-center gap-2"><input type="checkbox" checked={includePayments} onChange={e=>setIncludePayments(e.target.checked)}/>Include payment register</label></div>
      <details><summary className="cursor-pointer text-xs text-forest-600">Add report notes (optional)</summary><textarea aria-label="Report notes" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={3000} rows={3} className={`${input} mt-3`} placeholder="Handover notes, explanations, or actions for review"/></details>
      <button type="submit" disabled={loading} className="rounded-lg bg-forest-700 text-white px-5 py-2.5 text-sm font-medium disabled:opacity-50">{loading?'Preparing report…':'Generate report'}</button></fieldset>{error&&<p role="alert" className="text-sm text-clay">{error}</p>}
    </form>
    {loading&&<p role="status" className="no-print text-sm text-forest-500">Preparing a consistent snapshot of your records…</p>}
    {result&&r&&<><div className="no-print flex flex-wrap justify-between gap-3 items-center"><div><p className="text-sm font-semibold">Report preview</p><p className="text-xs text-forest-500 mt-1">Prepared {stamp(r.generatedAt)} EAT. Generate again to apply changed filters.</p></div><div className="flex flex-wrap gap-2"><button disabled={loading} onClick={exportBookings} className="rounded-lg border border-forest-200 px-3 py-2 text-xs bg-white">Bookings CSV</button><button disabled={loading} onClick={exportPayments} className="rounded-lg border border-forest-200 px-3 py-2 text-xs bg-white">Payments CSV</button><button disabled={loading} onClick={()=>window.print()} className="rounded-lg bg-forest-700 text-white px-4 py-2 text-xs font-semibold">Print / save PDF</button></div></div>
      <article id="report-content" className="professional-report">
        <header className="report-masthead"><div className="report-brand">SERENE SPA<span>REPORTS & RECORDS</span></div><p className="report-kicker">{allowBranchFilter?'Management review':'Branch operations'}</p><h1>{allowBranchFilter?'Business performance report':'Collections & operations report'}</h1><p className="report-subtitle">{date(r.range.from)} – {date(new Date(Date.parse(r.range.to)-1).toISOString())}</p><div className="report-metadata"><div><small>Reporting scope</small><strong>{r.scope.branchName}</strong><span>{result.provider} · {result.service}</span></div><div><small>Prepared by</small><strong>{result.preparedBy}</strong><span>{stamp(r.generatedAt)} EAT</span></div><div><small>Report reference</small><strong>SR-{r.generatedAt.replace(/\D/g,'').slice(0,14)}</strong><span>Internal business use · TZS</span></div></div></header>
        <div className="report-body">
          <Section index="01" title="Executive summary" note="A concise view of the selected reporting period.">
            <div className="report-metrics">{[['Collections',money(r.totals.collected),'Payments received · TZS'],['Bookings',r.totals.bookings,`${r.totals.completed} completed`],['Booking value',money(r.totals.bookingValue),'Non-cancelled bookings · TZS'],['Outstanding',money(r.totals.outstanding),'Current unpaid balance · TZS']].map(([label,value,note])=><div key={label}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>)}</div>
            <p className="report-summary">The selected scope recorded <strong>{r.totals.bookings} bookings</strong> and received <strong>{money(r.totals.collected)} TZS</strong> across {r.totals.paymentCount} payments. {r.totals.completed} bookings are completed, {r.totals.cancelled} cancelled, and {r.totals.inProgress} remain pending, active, on hold, or awaiting payment.</p>
            <Table headers={['Measure','This period','Previous period','Change']}><tr><td>Collections (TZS)</td><td className="numeric">{money(r.totals.collected)}</td><td className="numeric">{money(r.previous.collected)}</td><td>{change(r.totals.collected,r.previous.collected)}</td></tr><tr><td>Bookings</td><td className="numeric">{r.totals.bookings}</td><td className="numeric">{r.previous.bookings}</td><td>{change(r.totals.bookings,r.previous.bookings)}</td></tr><tr><td>Completed bookings</td><td className="numeric">{r.totals.completed}</td><td className="numeric">{r.previous.completed}</td><td>{change(r.totals.completed,r.previous.completed)}</td></tr></Table><p className="report-footnote">Comparison: {stamp(r.range.previousFrom)} to {stamp(r.range.previousTo)} EAT, the preceding equal-length period. Today may be incomplete.</p>
          </Section>
          <Section index="02" title="Collections & daily activity" note="Collections follow payment receipt dates, including payments for older bookings.">
            <Table headers={['Payment method','Transactions','Collected (TZS)','Share']} >{r.methods.length?r.methods.map(m=><tr key={m.name}><td className="capitalize">{status(m.name)}</td><td className="numeric">{m.transactions}</td><td className="numeric">{money(m.collected)}</td><td className="numeric">{r.totals.collected?(m.collected/r.totals.collected*100).toFixed(1):'0'}%</td></tr>):<None cols={4}/>}<tr className="report-total"><td>Total collections</td><td className="numeric">{r.totals.paymentCount}</td><td className="numeric">{money(r.totals.collected)}</td><td/></tr></Table>
            <h3 className="report-subheading">Daily activity</h3><Table headers={['Date','Bookings','Payments','Collected (TZS)']} >{r.days.filter(d=>d.bookings||d.transactions).length?r.days.filter(d=>d.bookings||d.transactions).map(d=><tr key={d.name}><td>{date(d.name)}</td><td className="numeric">{d.bookings}</td><td className="numeric">{d.transactions}</td><td className="numeric">{money(d.collected)}</td></tr>):<None cols={4}/>}</Table><p className="report-footnote">Dates with no bookings or payments are omitted. Figures are recorded activity, not a physical cash-count reconciliation.</p>
          </Section>
          <Section index="03" title="Service & team performance" note="Ranked by collections. Revenue is attributed to the booking’s primary service and provider.">
            {allowBranchFilter&&!r.scope.branchId&&<><h3 className="report-subheading">Branch contribution</h3><Performance rows={r.branches} label="Branch"/></>}
            <h3 className="report-subheading">Services</h3><Performance rows={r.services} label="Service"/>
            <h3 className="report-subheading">Providers</h3><Performance rows={r.providers} label="Provider"/>
          </Section>
          <Section index="04" title="Exceptions & follow-up" note="Outstanding amounts are current balances on non-cancelled bookings created in this period.">
            <div className="report-callouts"><p><strong>{r.totals.cancelled}</strong> cancellations</p><p><strong>{r.totals.noShows}</strong> reported no-shows</p><p><strong>{outstanding.length}</strong> bookings with a balance</p></div>
            <Table headers={['Booking / customer','Service','Branch / room','Outstanding (TZS)']} >{outstanding.length?outstanding.map(b=><tr key={b.id}><td><strong>#{b.id}</strong> {b.customer_name}</td><td>{b.service_name}</td><td>{b.branch_name} / {b.room_name}</td><td className="numeric">{money(Math.max(0,Number(b.amount_due)-Number(b.amount_paid)))}</td></tr>):<None cols={4}/>}<tr className="report-total"><td colSpan={3}>Outstanding total</td><td className="numeric">{money(r.totals.outstanding)}</td></tr></Table>
          </Section>
          {result.bookings&&<Section index="A" title="Booking register" note="Bookings created during the selected period. Paid amounts include all payments to date."><Table headers={['Booking / date','Customer / service','Branch / room','Provider / status','Value','Paid','Balance']} >{r.bookings.length?r.bookings.map(b=><tr key={b.id}><td>#{b.id}<small>{stamp(b.created_at)}</small></td><td>{b.customer_name}<small>{b.service_name}{b.extra_services?` + ${b.extra_services}`:''}</small></td><td>{b.branch_name}<small>{b.room_name}</small></td><td>{b.provider_name}<small className="capitalize">{status(b.status)}</small></td><td className="numeric">{money(Number(b.amount_due))}</td><td className="numeric">{money(Number(b.amount_paid))}</td><td className="numeric">{b.status==='cancelled'?'—':money(Math.max(0,Number(b.amount_due)-Number(b.amount_paid)))}</td></tr>):<None cols={7}/>}</Table></Section>}
          {result.payments&&<Section index="B" title="Payment register" note="Every payment received during the selected period. All amounts are in TZS."><Table headers={['Payment / received','Booking / customer','Branch','Method','Recorded by','Amount']} >{r.payments.length?r.payments.map(p=><tr key={p.id}><td>#{p.id}<small>{stamp(p.created_at)}</small></td><td>#{p.booking_id} {p.customer_name}</td><td>{p.branch_name}</td><td className="capitalize">{status(p.method)}</td><td>{p.recorded_by_name||'—'}</td><td className="numeric">{money(Number(p.amount))}</td></tr>):<None cols={6}/>}<tr className="report-total"><td colSpan={5}>Total collections</td><td className="numeric">{money(r.totals.collected)}</td></tr></Table></Section>}
          <section className="report-closing"><h2>Notes & review</h2>{result.notes&&<p className="whitespace-pre-wrap">{result.notes}</p>}<p className="report-footnote">Amounts are in Tanzanian shillings (TZS); dates use East Africa Time (UTC+3). Booking value excludes cancellations. Collections and booking value use different date bases and should not be subtracted to derive debt. Statuses and balances reflect the time this report was generated. This operational report does not calculate profit, tax liability, or expenses.</p><div className="report-signoff"><div>Prepared by<strong>{result.preparedBy}</strong></div><div>Reviewed by<span>________________________</span></div><div>Review date<span>________________________</span></div></div></section>
        </div><footer className="report-footer">Serene Spa · {r.scope.branchName} · Confidential business report</footer>
      </article>
    </>}
    {!result&&!loading&&<div className="no-print rounded-2xl border border-dashed border-forest-200 p-10 text-center"><h2 className="font-display text-2xl">Ready when you are.</h2><p className="text-sm text-forest-500 mt-2">Choose your period and filters, then generate a report ready to review, print, or share.</p></div>}
  </div>;
}
