'use client';

import { useEffect, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { useBranches } from '@/lib/useBranches';
import type { SpaAnalytics, AnalyticsRank } from '@/lib/analytics';

const number = (n: number) => new Intl.NumberFormat('en-TZ', {maximumFractionDigits: 0}).format(n);
const compact = (n: number) => new Intl.NumberFormat('en', {notation: 'compact', maximumFractionDigits: 1}).format(n);
const dateLabel = (s: string) => new Date(s).toLocaleDateString('en-GB', {day: 'numeric', month: 'short', timeZone: 'Africa/Nairobi'});
const today = () => new Date(Date.now() + 10800000).toISOString().slice(0, 10);
const statusNames: Record<string, string> = {completed: 'Completed', cancelled: 'Cancelled', active: 'In progress', pending: 'Pending', awaiting_payment: 'Awaiting payment', on_hold: 'On hold'};
const statusColors: Record<string, string> = {completed: '#2f6b58', cancelled: '#b1614f', active: '#7fab9d', pending: '#c2933d', awaiting_payment: '#8b86ac', on_hold: '#a4aaa7'};

function Panel({title, subtitle, children, action}: {title: string; subtitle?: string; children: ReactNode; action?: ReactNode}) {
  return <section className="rounded-2xl border border-forest-100 bg-white p-5 sm:p-6 min-w-0"><div className="flex items-start justify-between gap-3 mb-5"><div><h2 className="font-semibold text-ink">{title}</h2>{subtitle && <p className="text-xs text-forest-500 mt-1">{subtitle}</p>}</div>{action}</div>{children}</section>;
}
function Change({value, previous}: {value: number; previous: number}) {
  if (previous === 0) return <span className="text-xs text-forest-500">{value > 0 ? 'No previous activity to compare' : 'No change from previous period'}</span>;
  const delta = (value - previous) / Math.abs(previous) * 100;
  return <span className={`text-xs ${delta >= 0 ? 'text-forest-600' : 'text-clay'}`}><strong>{delta > 0 ? '↑' : delta < 0 ? '↓' : '→'} {Math.abs(delta).toFixed(1)}%</strong> <span className="text-forest-500">vs previous period</span></span>;
}
function Empty({children = 'No activity in this period.'}: {children?: ReactNode}) { return <p className="py-10 text-sm text-center text-forest-500">{children}</p>; }
function Ranking({rows, kind}: {rows: AnalyticsRank[]; kind: 'services' | 'providers'}) {
  const [expanded, setExpanded] = useState(false);
  const maximum = Math.max(1, ...rows.map(r => r.revenue));
  return <>{rows.length === 0 ? <Empty /> : <div className="space-y-5">{(expanded ? rows : rows.slice(0, 5)).map((row, i) => <div key={row.id ?? 'none'}><div className="flex justify-between gap-4 text-sm mb-2"><div className="flex gap-3 min-w-0"><span className="text-forest-300 tabular-nums">{String(i + 1).padStart(2, '0')}</span><span className="truncate font-medium" title={row.name}>{row.name}</span></div><span className="font-semibold tabular-nums whitespace-nowrap">{number(row.revenue)}</span></div><div className="ml-7 h-1.5 rounded-full bg-forest-50 overflow-hidden"><div className="h-full rounded-full bg-forest-400" style={{width: `${row.revenue / maximum * 100}%`}} /></div><p className="ml-7 mt-1.5 text-xs text-forest-500">{row.bookings} bookings{kind === 'providers' ? ` · ${row.completed} completed` : ''}</p></div>)}</div>}{rows.length > 5 && <button onClick={() => setExpanded(!expanded)} className="mt-5 text-xs font-semibold text-forest-600 underline">{expanded ? 'Show top 5' : `View all ${rows.length}`}</button>}</>;
}
function RevenueChart({days}: {days: SpaAnalytics['days']}) {
  const [active, setActive] = useState<number | null>(null);
  const monthly = days.length > 90;
  const groups = new Map<string, {date: string; revenue: number; bookings: number}>();
  for (const day of days) { const key = monthly ? day.date.slice(0, 7) : day.date; const row = groups.get(key) || {date: monthly ? `${key}-01` : key, revenue: 0, bookings: 0}; row.revenue += day.revenue; row.bookings += day.bookings; groups.set(key, row); }
  const points = [...groups.values()];
  const max = Math.max(1, ...points.map(d => d.revenue));
  const selected = active === null ? null : points[active];
  const width = 760, height = 210, left = 55, bottom = 180;
  const step = (width - left - 12) / Math.max(points.length, 1);
  return <><div className="h-8 text-xs text-forest-500" aria-live="polite">{selected ? <><strong className="text-ink">{monthly ? selected.date.slice(0, 7) : dateLabel(selected.date)}</strong> · {number(selected.revenue)} TZS · {selected.bookings} bookings</> : `${monthly ? 'Monthly' : 'Daily'} collected revenue · hover or focus a bar for details`}</div><svg viewBox={`0 0 ${width} ${height}`} className="w-full" role="group" aria-label="Collected revenue over time">{[0, 0.5, 1].map(f => <g key={f}><line x1={left} x2={width} y1={bottom - f * 145} y2={bottom - f * 145} stroke="#e9efec" strokeDasharray="4 4" /><text x={left - 10} y={bottom - f * 145 + 4} textAnchor="end" fill="#638076" fontSize="11">{compact(max * f)}</text></g>)}{points.map((d, i) => <g key={d.date}><rect x={left + i * step + 1} y={bottom - d.revenue / max * 145} width={Math.max(1, step - 3)} height={Math.max(1, d.revenue / max * 145)} rx={Math.min(4, step / 4)} fill={active === i ? '#c2933d' : '#2f6b58'} tabIndex={0} role="img" aria-label={`${d.date}: ${number(d.revenue)} TZS, ${d.bookings} bookings`} onMouseEnter={() => setActive(i)} onMouseLeave={() => setActive(null)} onFocus={() => setActive(i)} onBlur={() => setActive(null)}><title>{d.date}: {number(d.revenue)} TZS</title></rect>{(i === 0 || i === points.length - 1 || i === Math.floor(points.length / 2)) && <text x={left + (i + 0.5) * step} y={202} textAnchor="middle" fill="#638076" fontSize="11">{dateLabel(d.date)}</text>}</g>)}</svg>{days.every(d => d.revenue === 0) && <p className="text-xs text-forest-500 mt-2">No payments were collected in this period.</p>}<details className="mt-3 text-xs text-forest-500"><summary className="cursor-pointer">View chart data</summary><div className="max-h-48 overflow-auto mt-2"><table className="w-full text-left"><thead><tr><th className="py-2">Date</th><th>Collected (TZS)</th><th>Bookings</th></tr></thead><tbody>{points.map(d => <tr key={d.date}><td className="py-1">{d.date}</td><td>{number(d.revenue)}</td><td>{d.bookings}</td></tr>)}</tbody></table></div></details></>;
}

export default function AdminAnalyticsPage() {
  const {branches} = useBranches();
  const [period, setPeriod] = useState('30');
  const [branch, setBranch] = useState('');
  const [from, setFrom] = useState(today());
  const [to, setTo] = useState(today());
  const [revision, setRevision] = useState(0);
  const [report, setReport] = useState<SpaAnalytics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => {
    let cancelled = false;
    async function load() {
      setLoading(true); setError('');
      try {
        const end = period === 'custom' ? Math.min(Date.parse(`${to}T00:00:00+03:00`) + 86400000, Date.now()) : Date.now();
        const start = period === 'custom' ? Date.parse(`${from}T00:00:00+03:00`) : Date.parse(`${today()}T00:00:00+03:00`) - (Number(period) - 1) * 86400000;
        if (!Number.isFinite(start) || !Number.isFinite(end) || start >= end || end - start > 367 * 86400000) throw new Error('Choose a valid date range of up to one year.');
        const query = new URLSearchParams({from: new Date(start).toISOString(), to: new Date(end).toISOString()});
        if (branch) query.set('branchId', branch);
        const data = await api.get<SpaAnalytics>(`/reports/analytics?${query}`);
        if (!cancelled) setReport(data);
      } catch (e) { if (!cancelled) setError(e instanceof Error ? e.message : 'Could not load analytics.'); }
      finally { if (!cancelled) setLoading(false); }
    }
    load(); return () => {cancelled = true;};
  }, [period, branch, from, to, revision]);
  function exportCsv() {
    if (!report) return;
    const csv = ['Date,Collected revenue (TZS),Bookings', ...report.days.map(d => `${d.date},${d.revenue},${d.bookings}`)].join('\r\n');
    const url = URL.createObjectURL(new Blob([csv], {type: 'text/csv;charset=utf-8;'}));
    const a = document.createElement('a'); a.href = url; a.download = `spa-analytics-${report.days[0]?.date || today()}.csv`; a.click(); URL.revokeObjectURL(url);
  }
  const completion = report && report.current.bookings ? report.current.completed / report.current.bookings * 100 : 0;
  const cancellation = report && report.current.bookings ? report.current.cancelled / report.current.bookings * 100 : 0;
  const peak = report?.hours.reduce((best, h) => h.bookings > best.bookings ? h : best, {hour: 0, bookings: 0});
  const input = 'rounded-lg border border-forest-100 bg-white px-3 py-2 text-sm text-forest-700 focus:outline-none focus:ring-2 focus:ring-forest-300';
  return <div className="space-y-6 pb-8">
    <header className="flex flex-wrap justify-between items-end gap-4"><div><p className="text-[10px] font-bold tracking-[0.22em] uppercase text-forest-500 mb-2">Business intelligence</p><h1 className="font-display text-4xl text-ink">Your spa, in perspective.</h1><p className="text-sm text-forest-500 mt-2">See what is growing, what is working, and what needs attention.</p></div><button onClick={exportCsv} disabled={!report || loading || !!error} className="rounded-lg border border-forest-200 px-4 py-2.5 text-sm font-medium bg-white disabled:opacity-40">Export data ↓</button></header>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-forest-50/70 p-3 border border-forest-100"><div className="flex flex-wrap gap-2 items-center"><label className="sr-only" htmlFor="analytics-branch">Branch</label><select id="analytics-branch" value={branch} onChange={e => setBranch(e.target.value)} className={input}><option value="">All branches</option>{branches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select><label className="sr-only" htmlFor="analytics-period">Date range</label><select id="analytics-period" value={period} onChange={e => setPeriod(e.target.value)} className={input}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="custom">Custom dates</option></select>{period === 'custom' && <><label className="text-xs">From <input aria-label="From date" type="date" value={from} max={today()} onChange={e => setFrom(e.target.value)} className={input} /></label><label className="text-xs">To <input aria-label="To date" type="date" value={to} min={from} max={today()} onChange={e => setTo(e.target.value)} className={input} /></label></>}</div><button onClick={() => setRevision(v => v + 1)} disabled={loading} className="text-xs font-semibold text-forest-600 px-3 py-2 disabled:opacity-40">↻ Refresh</button></div>
    {loading ? <div role="status" aria-label="Loading analytics" className="space-y-5"><div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{[0,1,2,3].map(i => <div key={i} className="h-36 bg-forest-50 rounded-2xl animate-pulse" />)}</div><div className="h-80 bg-forest-50 rounded-2xl animate-pulse" /></div> : error ? <div role="alert" className="rounded-2xl border border-clay/30 bg-white p-8"><h2 className="font-semibold">Analytics could not be loaded</h2><p className="text-sm text-clay mt-2">{error}</p><button onClick={() => setRevision(v => v + 1)} className="mt-4 text-sm underline">Try again</button></div> : report && <>
      <div className="flex flex-wrap justify-between gap-2 text-xs text-forest-500"><span>{dateLabel(report.range.from)} – {dateLabel(report.range.to)} · Compared with the preceding equal-length period</span><span>Updated {new Date(report.updatedAt).toLocaleTimeString('en-GB', {hour:'2-digit',minute:'2-digit',timeZone:'Africa/Nairobi'})} EAT</span></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
        <div className="rounded-2xl bg-forest-800 p-6 text-white"><div className="flex justify-between text-xs text-forest-200"><span>Collected revenue</span><span>TZS</span></div><p className="text-3xl font-semibold tracking-tight mt-4 mb-3 tabular-nums break-words">{number(report.current.revenue)}</p><div className="bg-white rounded-md px-2 py-1 inline-block"><Change value={report.current.revenue} previous={report.previous.revenue} /></div></div>
        <div className="rounded-2xl border border-forest-100 bg-white p-6"><p className="text-xs text-forest-500">Total bookings</p><p className="text-3xl font-semibold tracking-tight mt-4 mb-3 tabular-nums">{number(report.current.bookings)}</p><Change value={report.current.bookings} previous={report.previous.bookings} /></div>
        <div className="rounded-2xl border border-forest-100 bg-white p-6"><p className="text-xs text-forest-500">Average booking value · TZS</p><p className="text-3xl font-semibold tracking-tight mt-4 mb-3 tabular-nums">{number(report.current.averageValue)}</p><Change value={report.current.averageValue} previous={report.previous.averageValue} /></div>
        <div className="rounded-2xl border border-forest-100 bg-white p-6"><p className="text-xs text-forest-500">Completion rate</p><p className="text-3xl font-semibold tracking-tight mt-4 mb-3 tabular-nums">{completion.toFixed(1)}<span className="text-xl text-forest-400">%</span></p><p className="text-xs text-forest-500">{report.current.completed} completed · {report.current.cancelled} cancelled</p></div>
      </div>
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-5"><div className="xl:col-span-2"><Panel title="Revenue over time" subtitle="Payments received during the selected period · TZS"><RevenueChart key={report.updatedAt} days={report.days} /></Panel></div><Panel title="Booking health" subtitle="Current status of bookings created in this period"><div className="flex items-end gap-2 mb-5"><span className="text-4xl font-semibold tabular-nums">{cancellation.toFixed(1)}%</span><span className="text-xs text-forest-500 pb-1">cancellation rate</span></div>{report.current.bookings ? <><div className="flex h-3 rounded-full overflow-hidden mb-5">{report.statuses.map(s => <div key={s.status} style={{width: `${s.count / report.current.bookings * 100}%`, background: statusColors[s.status] || '#a4aaa7'}} title={`${statusNames[s.status] || s.status}: ${s.count}`} />)}</div><div className="space-y-3">{report.statuses.map(s => <div key={s.status} className="flex justify-between text-sm"><span className="flex items-center gap-2 text-forest-600"><span className="w-2 h-2 rounded-full" style={{background: statusColors[s.status] || '#a4aaa7'}} />{statusNames[s.status] || s.status}</span><span className="font-medium tabular-nums">{s.count}</span></div>)}</div></> : <Empty>No bookings yet.</Empty>}</Panel></div>
      <Panel title="Branch performance" subtitle="Compare collections and completed bookings" action={<Link href="/admin/reports" className="text-xs font-semibold text-forest-600 whitespace-nowrap">Detailed reports ↗</Link>}><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead className="text-[11px] uppercase tracking-wide text-forest-500 border-b border-forest-100"><tr><th className="pb-3 font-medium">Branch</th><th className="pb-3 px-4 font-medium text-right">Bookings</th><th className="pb-3 px-4 font-medium text-right">Completed</th><th className="pb-3 font-medium text-right">Collected · TZS</th><th className="pb-3 pl-6 font-medium hidden md:table-cell">Revenue share</th></tr></thead><tbody>{report.branches.map(b => <tr key={b.id ?? 'none'} className="border-b last:border-0 border-forest-50"><td className="py-4 font-medium">{b.name}</td><td className="px-4 text-right tabular-nums">{b.bookings}</td><td className="px-4 text-right tabular-nums">{b.completed}</td><td className="text-right font-semibold tabular-nums">{number(b.revenue)}</td><td className="pl-6 w-40 hidden md:table-cell"><div className="h-2 bg-forest-50 rounded-full"><div className="h-full bg-forest-400 rounded-full" style={{width: `${report.current.revenue > 0 ? b.revenue / report.current.revenue * 100 : 0}%`}} /></div></td></tr>)}</tbody></table>{!report.branches.length && <Empty>No branches to display.</Empty>}</div></Panel>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Panel title="Top services" subtitle="Ranked by collected revenue · TZS"><Ranking key={`s-${report.updatedAt}`} rows={report.services} kind="services" /></Panel><Panel title="Provider performance" subtitle="Ranked by collected revenue · TZS"><Ranking key={`p-${report.updatedAt}`} rows={report.providers} kind="providers" /></Panel></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5"><Panel title="When bookings are recorded" subtitle="Booking creation time · East Africa Time"><div className="flex items-end gap-1 h-28 mt-4">{report.hours.map(h => <div className="flex-1 h-full flex items-end" key={h.hour}><div tabIndex={0} title={`${String(h.hour).padStart(2,'0')}:00 — ${h.bookings} bookings`} aria-label={`${h.hour}:00, ${h.bookings} bookings`} className="w-full bg-forest-300 hover:bg-honey-500 rounded-t-sm min-h-[2px]" style={{height:`${h.bookings / Math.max(1, peak?.bookings || 0) * 100}%`}} /></div>)}</div><div className="flex justify-between text-[10px] text-forest-500 mt-2"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div><p className="text-xs text-forest-500 mt-5">{peak?.bookings ? `Most bookings were recorded between ${String(peak.hour).padStart(2,'0')}:00 and ${String(peak.hour+1).padStart(2,'0')}:00.` : 'Activity will appear here when bookings are recorded.'}</p></Panel><Panel title="Needs attention" subtitle="Current balances and stock levels"><div className="divide-y divide-forest-100"><div className="pb-4 flex justify-between items-start gap-4"><div><p className="text-sm font-medium">Outstanding payments</p><p className="text-xs text-forest-500 mt-1">Current balance on this period’s bookings</p></div><span className="font-semibold text-clay tabular-nums whitespace-nowrap">{number(report.current.outstanding)} <span className="text-xs font-normal">TZS</span></span></div><div className="py-4 flex justify-between items-start gap-4"><div><p className="text-sm font-medium">Stock on hand value</p><p className="text-xs text-forest-500 mt-1">{branch ? 'Selected branch' : 'Central catalog + all branches'} · priced items</p></div><span className="font-semibold tabular-nums whitespace-nowrap">{number(report.inventory.value)} <span className="text-xs font-normal">TZS</span></span></div><div className="pt-4"><Link href="/admin/inventory" className="flex justify-between text-sm font-medium"><span>{report.inventory.lowStock.length ? `${report.inventory.lowStock.length} branch stock alerts` : 'No low-stock alerts'}</span><span className="text-forest-500">Inventory ↗</span></Link>{report.inventory.lowStock.length > 0 && <details className="mt-3 text-xs"><summary className="cursor-pointer text-clay">Review items at or below minimum</summary><div className="max-h-48 overflow-auto mt-2 space-y-2">{report.inventory.lowStock.map(s => <div key={s.id} className="flex justify-between gap-3 rounded-lg bg-sand-100 p-2"><span>{s.item} · {s.branch}</span><span className="whitespace-nowrap">{s.quantity} / min {s.minimum}</span></div>)}</div></details>}</div></div></Panel></div>
      <details className="text-xs text-forest-500 border-t border-forest-100 pt-4"><summary className="cursor-pointer">How these numbers are calculated</summary><p className="mt-3 leading-relaxed max-w-4xl">Revenue uses the date each payment was received. Booking counts use the date the booking was created, with current completion status. Average booking value uses the amount due on non-cancelled bookings. Payments for older bookings are included in revenue when received. Service and provider revenue follows the booking’s primary service and provider. Stock and outstanding balances show their current values, not a historical snapshot. All chart dates and times use East Africa Time. The current day is still in progress.</p></details>
    </>}
  </div>;
}
